development:
  adapter: postgresql
  database: curriculous_dev
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: curriculous_test
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: curriculous_live
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
