defaults:
  precompile_assets: true
  asset_dependencies:
  # default
  - app/assets
  - lib/assets
  - vendor/assets
  - Gemfile.lock
  - config/application.rb
  - config/routes.rb
  # custom
  - .secret 
